# Generated by Django 2.2.2 on 2019-06-23 21:46

import commerce.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', commerce.models.user.CommerceUserManager()),
            ],
        ),
    ]
