# Generated by Django 2.2.2 on 2019-06-24 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('price', models.IntegerField(default=0, verbose_name='가격')),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='product_image')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='판매 중')),
                ('description', models.TextField(blank=True, null=True)),
                ('shipping_method', models.CharField(choices=[('PREPAY', '선결제'), ('FREE', '무료')], default='FREE', max_length=2)),
                ('shipping_price', models.IntegerField(default=0, verbose_name='배송비')),
                ('can_bundle', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='product_image')),
                ('stock', models.IntegerField(default=0, verbose_name='재고')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('size', models.CharField(choices=[('S', '소'), ('M', '중'), ('L', '대'), ('XL', '특대')], default='M', max_length=2)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='commerce.Product')),
            ],
            options={
                'verbose_name': '상품옵션',
                'verbose_name_plural': '상품옵션',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='공급자명')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='주소')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='전화번호')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '공급자',
                'verbose_name_plural': '공급자',
            },
        ),
        migrations.CreateModel(
            name='PurchaseLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paid_price', models.IntegerField(default=0, verbose_name='결제 금액')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='주문 요청 사항')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '구매 내역',
                'verbose_name_plural': '구매 내역',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0, verbose_name='구매 수량')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_rows', to='commerce.ProductOption')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='commerce.PurchaseLog')),
            ],
            options={
                'verbose_name': '구매 정보',
                'verbose_name_plural': '구매 정보',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='commerce.Provider'),
        ),
        migrations.AddField(
            model_name='user',
            name='cart_items',
            field=models.ManyToManyField(blank=True, related_name='users', to='commerce.ProductOption', verbose_name='장바구니'),
        ),
    ]
