# Generated by Django 2.2.2 on 2019-06-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_auto_20190624_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_method',
            field=models.CharField(choices=[('PREPAY', '선결제'), ('FREE', '무료')], default='FREE', max_length=7),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='size',
            field=models.CharField(choices=[('S', '소'), ('M', '중'), ('L', '대'), ('XL', '특대')], default='M', max_length=3),
        ),
    ]
