# Generated by Django 2.2.2 on 2019-06-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_auto_20190624_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoption',
            name='image',
        ),
        migrations.AddField(
            model_name='productoption',
            name='color',
            field=models.CharField(default='white', max_length=30, verbose_name='색상'),
        ),
    ]
